"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
command_timeout = 1200
palette = "kinoite"

format = """
$username$hostname$directory$git_branch$git_status$fill$cmd_duration
$character
"""

[palettes.kinoite]
fg = "#d9e0ee"
blue = "#7aa2f7"
green = "#9ece6a"
yellow = "#e0af68"
red = "#f7768e"
gray = "#6c7086"

[os]
disabled = false
format = "[$symbol ]($style)"
style = "bold blue"

[os.symbols]
Fedora = ""

[username]
show_always = false
style_user = "bold green"
style_root = "bold red"
format = "[$user ]($style)"

[hostname]
ssh_only = true
style = "bold yellow"
format = "[@$hostname ]($style)"

[directory]
style = "bold fg"
truncation_length = 4
truncate_to_repo = false
read_only = " 󰌾"
format = "[$path]($style)[$read_only]($red) "

[git_branch]
symbol = " "
style = "bold blue"
format = "[$symbol$branch ]($style)"

[git_status]
style = "bold yellow"
format = "([$all_status$ahead_behind ]($style))"

[fill]
symbol = " "

[cmd_duration]
min_time = 800
style = "gray"
format = "[${duration}]($style)"

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"
vimcmd_symbol = "[❮](bold blue)"

[package]
disabled = true
