name: build-amd
on:
  # schedule:
  #   - cron:
  #       "00 06 * * *" # build at 06:00 UTC every day
  # push:
  #   branches:
  #     - main
  pull_request:
  workflow_dispatch:

jobs:
  build-amd:
    uses: ./.github/workflows/build-image.yml
    with:
      workflow_name: build-amd
      display_name: AMD
      recipe: recipe-amd.yml
    secrets: inherit
