name: build-nvidia
on:
  # schedule:
  #   - cron:
  #       "00 06 * * *" # build at 06:00 UTC every day
  # push:
  #   branches:
  #     - main
  pull_request:
  workflow_dispatch:

jobs:
  build-nvidia:
    uses: ./.github/workflows/build-image.yml
    with:
      workflow_name: build-nvidia
      display_name: NVIDIA
      recipe: recipe-nvidia.yml
    secrets: inherit
