name: reusable-image-build

on:
  workflow_call:
    inputs:
      workflow_name:
        required: true
        type: string
      display_name:
        required: true
        type: string
      recipe:
        required: true
        type: string

concurrency:
  group: ${{ inputs.workflow_name }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  bluebuild:
    name: Build Custom ${{ inputs.display_name }} Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Build Custom ${{ inputs.display_name }} Image
        uses: blue-build/github-action@v1.11
        with:
          recipe: ${{ inputs.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event_name == 'pull_request' && github.event.number || '' }}
          verify_install: true
          maximize_build_space: true
          max_layers: 256
          use_cache: true
          retry_push_count: 3
          use_unstable_cli: false
          skip_checkout: true
